version: '3.5'


services:
  # SERVIDOR MYSQL
  mysql:
    build: 
      context: ./mysql/
    container_name: tw-mysql
    hostname: tw-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=twmysql2022
      - MYSQL_USER=willian
      - MYSQL_PASSWORD=will2022
      - MYSQL_DATABASE=tw-mysql-curso
    volumes:
      - db-volumes:/var/lib/mysql
    networks:
      - tw-mysql-network


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - tw-mysql-network


volumes:
  db-volumes:


networks:
  tw-mysql-network:
    driver: bridge
