version: '3.8'
services:
  # SERVIDOR MYSQL
  mysql:
    build: 
      context: ./mysql/
    container_name: tw-mysql
    hostname: tw-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - db-volumes:/var/lib/mysql
    networks:
      - tw-mysql-network


  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - tw-mysql-network


volumes:
  db-volumes:


networks:
  tw-mysql-network:
    driver: bridge
